### ISSUE TITLE
 Changes in TabList not function properly.

### ISSUE THREAD

**Issue by BlackwingedCrow** [Ironhippy/AbsentChat#1]
Hi I have your plugin on my server in use . I can change the nickname in the chat with the plugin . As well as in the TabList . However, the change was no longer visible after a restart . Only the chat had changed. 

Edit: 

Okay I got me again looked at seemingly the function is overridden by a Scoreboard .

e.g.: https://www.spigotmc.org/resources/thirst.3316/

Idea:
Can you also install the option " says " to change the chat , such as a colon .

**Comment by Ironhippy** [comment]
Could you elaborate please? I'm sorry, I'm bad with interpreting text.

**Comment by Flashera** [comment]
For the first thing, not sure why that would happen in a restart, do you mean reload? If that's the case try relogging and telling your players to as well.

For the second thing, you can, go to the main server directory abd go into mstore. There shod be a channels folder, go into it. Now open local.json and edit! Make sure you use the right bracket tags though!

**Comment by BlackwingedCrow** [comment]
Okay this works


Is there a command prefixes set , because that are not taken from Permissions Ex .

**Comment by Flashera** [comment]
Prefixes are only given in global chats to allow for nicknames more efficiently, if you want cours you can use the /ch color coomand, if ypu want donor colours, it would be wise to run the command through Buycraft/whatever you use.

**Comment by BlackwingedCrow** [comment]
But there are config to set a prefix is a possibility in the player . I would only be a command that love .

In addition, you can update it in a later set up the one via / < first letter of a channel > to send a short message on a channel . Without that one . In the joinen needs and then also everyone hears How e.g .: in Hero Chat .

Then the plugin would be perfect

**Comment by Flashera** [comment]
You can. Rype the chat shortcut with the message after. As of now there are no prefixes with Absenchat. Do you mean you can't type :? We're already aware if this issue.
